language: ruby
rvm:
  - 2.3.1

services:
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database correctaddressdb;' -U postgres